[package]
name = "athena"
version = "0.1.0"
edition = "2021"

[dependencies]
sea-orm = { version = "1" }
dotenvy = "0.15.0"
serde = { version = "1", features = ["derive"] }
athena_macros = { path = "../athena_macros" }
bitflags = "2.3"
thiserror = "2"